//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the category name cannot exceed 75 characters..
        /// </summary>
        public static string CategoryNameLength {
            get {
                return ResourceManager.GetString("CategoryNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A category name is required..
        /// </summary>
        public static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category with id &apos;{0}&apos; was not found..
        /// </summary>
        public static string CategoryNotFound {
            get {
                return ResourceManager.GetString("CategoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string InvalidDtoData {
            get {
                return ResourceManager.GetString("InvalidDtoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product category name is required..
        /// </summary>
        public static string ProductCategoryRequired {
            get {
                return ResourceManager.GetString("ProductCategoryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product cost cannott be less than null..
        /// </summary>
        public static string ProductCostNotBeLessThanNull {
            get {
                return ResourceManager.GetString("ProductCostNotBeLessThanNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the product description cannot exceed 300 characters..
        /// </summary>
        public static string ProductDescriptionLength {
            get {
                return ResourceManager.GetString("ProductDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the product name cannot exceed 75 characters..
        /// </summary>
        public static string ProductNameLength {
            get {
                return ResourceManager.GetString("ProductNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product name is required..
        /// </summary>
        public static string ProductNameRequired {
            get {
                return ResourceManager.GetString("ProductNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product with id &apos;{0}&apos; was not found..
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A product provider name is required..
        /// </summary>
        public static string ProductProviderRequired {
            get {
                return ResourceManager.GetString("ProductProviderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of the product description cannot exceed 75 characters..
        /// </summary>
        public static string ProviderNameLength {
            get {
                return ResourceManager.GetString("ProviderNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A provider name is required..
        /// </summary>
        public static string ProviderNameRequired {
            get {
                return ResourceManager.GetString("ProviderNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provider with id &apos;{0}&apos; was not found..
        /// </summary>
        public static string ProviderNotFound {
            get {
                return ResourceManager.GetString("ProviderNotFound", resourceCulture);
            }
        }
    }
}
